server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: localhost:2181

  devtools:
    restart:
      enabled: true  #设置开启热部署

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.4:3306/charles?useSSL=false&serverTimezone=UTC
    username: root
    password: 233666

